In [1]:
import glob
import os
import pandas as pd
import numpy as np
import math
import re

In [217]:
file_list = []
action = "C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data\\action"
# clab = "C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data\\action\\clab"
# onehand = "C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data\\action\\onehand"
# twohands = "C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data\\action\\twohands"

In [219]:
os.chdir(action)
os.getcwd()

'C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data\\action'

In [221]:
file_list = glob.glob(os.path.join('.\\*'))
file_list

['.\\clab', '.\\onehand', '.\\twohands']

In [253]:
a= [1,2,3,2,3,4,5]
a.pop()
a

[1, 2, 2, 3, 4, 5]

In [254]:
id_list = []
column_list = []
column_list = ['frame_num']
count = 0
for i in range(32):
    column_list.extend(["3d_x"+str(i),"3d_y"+str(i),"3d_z"+str(i)])
df_real = pd.DataFrame(columns=column_list)
for x in file_list:
    temp = action+x[1:]
    os.chdir(temp)
    file_list2 = glob.glob(os.path.join('.\\*'))
    for y in file_list2:
        file_id = y.split("_")[-1]
        df_test = pd.read_csv(y+"\\0.csv_file\\joint_info.csv")
        num = df_test['frame_num'].unique()
        for i in range(len(num)):
            id_list.append(file_id)
            temp = df_test['frame_num'] == i+1
            df_temp = df_test[temp]
            row_list = [str(i+1)]
            for index,row in df_temp.iterrows():
                n = index+1
                row_list.extend([row[3],row[4],row[5]])
            try:
                df_real.loc[count] = row_list
                count+=1
            except:
                id_list.pop(count)

In [257]:
df_real.insert(0,'id',id_list)
df_real

,id,frame_num,3d_x0,3d_y0,3d_z0,3d_x1,3d_y1,3d_z1,3d_x2,3d_y2,...,3d_z28,3d_x29,3d_y29,3d_z29,3d_x30,3d_y30,3d_z30,3d_x31,3d_y31,3d_z31
0,clab01,1,638.943,404.637,-4.80216,640.183,347.546,-1.16950,641.388,302.097,...,-16.12650,666.631,184.227,75.6139,618.332,174.488,-62.30750,618.492,191.927,-66.3222
1,clab01,2,637.082,407.058,-10.28780,639.011,349.410,-4.60539,640.885,303.643,...,-25.50740,666.078,185.848,73.9561,615.532,176.540,-70.61940,619.835,191.154,-62.7278
2,clab01,3,637.098,406.833,-10.24700,638.706,349.108,-5.50555,640.398,303.382,...,-15.44280,666.637,185.697,76.1861,618.325,176.286,-62.66440,617.699,191.602,-69.1262
3,clab01,4,637.410,407.627,-9.32994,639.542,349.996,-3.05517,641.622,304.353,...,-8.64403,667.709,187.808,79.4837,620.521,175.821,-56.43190,618.138,191.794,-67.7285
4,clab01,5,637.361,406.989,-9.48610,639.243,349.080,-3.94151,641.054,303.274,...,-7.31048,665.635,184.450,73.8549,620.683,178.290,-55.90900,614.448,192.670,-78.7439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10349,th10,336,648.295,392.645,22.07060,649.643,330.443,26.02370,650.754,281.270,...,46.15380,683.625,157.751,123.0650,638.381,150.538,-5.86930,626.790,157.275,-39.9998
10350,th10,337,648.563,392.665,22.83070,650.001,330.369,27.03870,651.184,281.092,...,48.00090,684.443,157.835,125.3770,639.054,151.308,-4.05284,627.571,157.194,-37.7317
10351,th10,338,648.376,392.567,22.28980,649.749,330.263,26.29580,650.920,281.100,...,50.60490,684.519,158.272,125.8500,639.982,150.475,-1.54105,627.581,157.122,-37.7068
10352,th10,339,648.475,392.572,22.58100,649.639,330.401,26.00780,650.627,281.264,...,55.47480,684.707,158.907,126.6000,641.747,149.313,3.22863,627.604,156.525,-37.5671
10353,th10,340,648.287,392.233,22.06840,649.367,330.159,25.26000,650.268,281.079,...,55.02590,684.107,157.870,124.8710,641.592,150.548,2.80819,626.818,157.057,-39.8108

In [261]:
os.chdir('C:\\Users\\Admin\\Desktop\\수업자료\\산학프로젝트\\kinect_data')
df_real.to_csv('./06_28.csv',index=False,encoding='cp949')

In [258]:
# all_data = []
# idx = 0
# for i in range(len(file_list)):
#     s = file_list[i]
#     s = re.findall('\(([^)]+)',s)
#     df_test = pd.read_csv(file_list[i])
#     df_real = pd.DataFrame(columns=['body_id','frame_num'])
# #     df_test.insert( 0, 'id', None)
#     df_test.drop('2d_x',axis=1,inplace=True)
#     df_test.drop('2d_y',axis=1,inplace=True)
#     id_list = []
#     count = 0
#     all_data.append(df_test)

In [259]:
# df_test = pd.read_csv(file_list[i])
# df_all = []
# num = df_test['frame_num'].unique()
# column_list = []
# column_list = ['frame_num']
# for i in range(32):
#     column_list.extend(["3d_x"+str(i),"3d_y"+str(i),"3d_z"+str(i)])
# df_real = pd.DataFrame(columns=column_list)
# display(df_real)
# for i in range(len(num)):
#     temp = df_test['frame_num'] == i+1
#     df_temp = df_test[temp]
#     row_list = [str(i+1)]
#     for index,row in df_temp.iterrows():
#         n = index+1
#         row_list.extend([row[3],row[4],row[5]])
#     df_real.loc[index] = row_list

# df_real.insert(0,'id','뭐로하지')
# df_real